# Generated by Django 3.2.13 on 2022-09-27 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('host', models.ManyToManyField(to='base.movieimg')),
                ('join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.box')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
